### 친구신청
POST http://localhost:8080/friends/request
Auth: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0M0B0ZXN0LmNvbSIsImV4cCI6MTY4MDMzMzQ5NH0.x9TvUM1KET2qwBWbzi-BwNwNXH70lvUlS-tRFf5hxunf5SpJDE0r2jeDe_KR5EkuGxgojHjwO4pgjJ6uopjXsQ
Content-Type: application/json

{
  "name": "test",
  "password": "123456789",
  "email": "test@test.com"
}

### 친구 요청 목록 조회
GET http://localhost:8080/friends/request?size=4
Auth: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiZXhwIjoxNjgwMzMzNTI2fQ.CZ5a04cd8aGsp_zBQFP600HRvkauFi1mZ3c7iorei_ta5J5gIR2v_hXF61GSKG3RCY6Y3mX7-aNAPiR86dzBKg
Content-Type: application/json

### 친구 요청 수락
POST http://localhost:8080/friends/request
Auth: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiZXhwIjoxNjgwMzMzNTI2fQ.CZ5a04cd8aGsp_zBQFP600HRvkauFi1mZ3c7iorei_ta5J5gIR2v_hXF61GSKG3RCY6Y3mX7-aNAPiR86dzBKg
